# This workflow will do a clean install of node dependencies,
# build the frontend, push files to remote dev and remotely build backend
# as soon as there are pushes to the main branch

name: Build & Deploy (Nightly)

on:
  push:
    branches: [ main ]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Build frontend
      run: |
        npm ci
        npm run build
    - name: Build .env
      run: printf "${{ secrets.LARAVEL_ENV_DEV }}" >> .env
    - name: Push project files to testing environment
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --exclude={'.git*','node_modules','.editorconfig','.env.*','vendor','storage'}
        path: ./
        remote_path: ${{ secrets.DEPLOY_PATH_DEV }}
        remote_host: ${{ secrets.DEPLOY_HOST_DEV }}
        remote_port: ${{ secrets.DEPLOY_PORT_DEV }}
        remote_user: ${{ secrets.DEPLOY_USER_DEV }}
        remote_key: ${{ secrets.DEPLOY_SSH_KEY_DEV }}
        remote_key_pass: ${{ secrets.DEPLOY_SSH_PHRASE_DEV }}
    - name: Build backend
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DEPLOY_HOST_DEV }}
        port: ${{ secrets.DEPLOY_PORT_DEV }}
        username: ${{ secrets.DEPLOY_USER_DEV }}
        key: ${{ secrets.DEPLOY_SSH_KEY_DEV }}
        passphrase: ${{ secrets.DEPLOY_SSH_PHRASE_DEV }}
        script: |
          cd ${{ secrets.DEPLOY_PATH_DEV }}
          composer update -qn
          composer install -qno --no-ansi --no-scripts --no-progress
          php8.3 artisan migrate --force
          php8.3 artisan config:clear
          php8.3 artisan config:cache
          php8.3 artisan route:clear
          php8.3 artisan route:cache
          php8.3 artisan view:clear
          php8.3 artisan view:cache
          rm -rf node_modules .git* .editorconfig .env.* *.config.js
