# This workflow will do a clean install of node dependencies,
# build the frontend, push files to remote prod and remotely build backend
# as soon as there are pushes to the main branch

name: Build & Deploy (Production)

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js 17
      uses: actions/setup-node@v3
      with:
        node-version: 17.x
    - name: Cache node_modules
      uses: actions/cache@v3
      id: node_modules-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install node packages
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: Build frontend
      run: npm run build
    - name: Build .env
      run: printf "${{ secrets.LARAVEL_ENV_PROD }}" >> .env
    - name: Push project files to testing environment
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --exclude={'.git*','node_modules','.editorconfig','.env.*'} --delete --delete-excluded
        # rsh: uptime
        path: ./
        remote_path: ${{ secrets.DEPLOY_PATH_PROD }}
        remote_host: ${{ secrets.DEPLOY_HOST_PROD }}
        remote_port: ${{ secrets.DEPLOY_PORT_PROD }}
        remote_user: ${{ secrets.DEPLOY_USER_PROD }}
        remote_key: ${{ secrets.DEPLOY_SSH_KEY_PROD }}
        remote_key_pass: ${{ secrets.DEPLOY_SSH_PHRASE_PROD }}
    - name: Build backend
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DEPLOY_HOST_PROD }}
        port: ${{ secrets.DEPLOY_PORT_PROD }}
        username: ${{ secrets.DEPLOY_USER_PROD }}
        key: ${{ secrets.DEPLOY_SSH_KEY_PROD }}
        passphrase: ${{ secrets.DEPLOY_SSH_PHRASE_PROD }}
        script: |
          cd ${{ secrets.DEPLOY_PATH_PROD }}
          composer update -qn
          composer install -qno --no-ansi --no-scripts --no-progress
          php artisan migrate --force
          php artisan config:clear
          php artisan config:cache
          php artisan route:clear
          php artisan route:cache
          php artisan view:clear
          php artisan view:cache
          rm -rf node_modules .git* .editorconfig .env.* *.config.js
